### ISSUE TITLE
Improve libvirt startup time if possible

### ISSUE THREAD

**Issue by rmohr** [kubevirt/libvirt#17]
Libvirt needs between 5-10 seconds in our test-runs to be started. It does a lot of auto-discovering which is in general good. I wonder if we can change some libvirt configurations and avoid some time-consuming and possibly unneeded checks on startup (e.g. we don't have dbus in the container, so no need to check for it, things like that). That would significantly improve test-time.

**Comment by rmohr** [comment]
@nertpinx maybe you have some ideas?

**Comment by nertpinx** [comment]
Some of the capabilities get cached, so if we pre-populate the cache during build time it might speed up some of it. It depends on the QEMU version, kernel version and libvirtd+qemu binary ctimes IIRC, so it should be OK, **just** for the tests, though. I'll see how that can be done easily.

**Comment by rmohr** [comment]
@nertpinx this would become more pressing now. I also have more concrete numbers. We roughly wait 10-12 seconds until libvirt is ready. Are there some easy improvements? E.g. tweak the config to not do some - in our case - unnecessary checks?

**Comment by nertpinx** [comment]
@rmohr We made some speedups thanks to better caching.  It arrived in v4.10.0 IIRC.  I have some other ideas but they are either tricky or require more massive refactoring of libvirt.  The main problem is that we don't know what's so slow for you without any profiling outputs.  Would it be possible to set up some profiling setup and run libvirt container couple of times so that we know what to concentrate on?

**Comment by rmohr** [comment]
> Would it be possible to set up some profiling setup and run libvirt container couple of times so that we know what to concentrate on?

@nertpinx the container is built here. I would suggest that you simply run the container. It needs that time on any start ... I think it is simpler for you than adding some profiling somehwere else.

**Comment by cynepco3hahue** [comment]
@nertpinx But will caching help, because we start each time new libvirt instance?

**Comment by nertpinx** [comment]
@cynepco3hahue The caching we have currently will not.  But we fixed a problem where caches were regenerated multiple times per one VM.  We are also currently working on fixing some firewall rules.  Cleaning them on daemon startup takes some significant time.  There are various things that could be improved but we first need to identify what parts of the initialization contribute to the startup time significantly.
The biggest improvement would, of course, come when libvirtd is split into daemons; I presume you didn't experience such a delay previously when libvirt daemon was part of the DaemonSet.
Since I'm currently concentrating on other priority tasks in other projects I asked @zippy2 for some investigation on this, hopefully he'll be able to provide some estimates and intermediate solution.
Beware that he might come to a conclusion that it is not worth investing in such intermediate solution in case the daemon split is closer/easier or in case it might complicate the split. But I'll leave that up to him.

**Comment by zippy2** [comment]
I haven't tried running libvirtd inside a container, but I did some profiling on my machine and here's what I found. The majority of startup time is taken by querying the qemu capabilities. The second slow down happens when starting network - libvirt inserts all these firewall rules which takes significant amount of time. Surprisingly, some time is spent querying host pm-* capabilities. This is because pm-is-supported is a shell script.
Anyway, I bet that if you'd copy libvirt capabilities into the container (/var/cache/libvirt/*) then libvirt would not need to build the caps from scratch and that would bring it up very fast.

**Comment by rmohr** [comment]
So here a few questions:

 * We know the qemu version at container build-time (can we start libvirt during  the container build once to not re-query the qemu capabilities?)
 * Will libvirtd also do all this network and and firewall discovery inside the container where no firewall is present?
 * Would libvirt still detect host capabilities correctly if we start libvirt at container build time and keep the cache? Or is the pm-* scripts thing isolated enough, so that we can keep the qemu cache but not the host capabilities cache?

**Comment by nertpinx** [comment]
I tried some things as well.  I ran it inside a clean container with no capabilities present and I cannot get it to take 4 seconds even.  Just in case someone wants to try (or tell me what I did wrong), this is what I used:
```shell
docker run \
  --name libvirtd --rm --net=host --pid=host --ipc=host --user=root --privileged \
  -v /:/host:Z -v /dev:/host-dev/:Z -v /sys:/host-sys:Z -it kubevirt/libvirt:latest \
  bash -c '/libvirtd.sh &
  time sh -c "
    while ! test -S /var/run/libvirt/libvirt-sock; do :; done;
    virsh capabilities";
  killall libvirtd'
```
So my guess is that there is something outside of the container that affects the startup time. Can you try running that on your machines? Would it be possible to try this script (I mean the "benchmark" part only) in a deployed k8s?

**Comment by nertpinx** [comment]
And to reply to @rmohr:

> So here a few questions:
> 
>     * We know the qemu version at container build-time (can we start libvirt during  the container build once to not re-query the qemu capabilities?)
> 

The capabilities can still be invalidated due to different kernel versions. But it is a question of how long does this really take...

>     * Will libvirtd also do all this network and and firewall discovery inside the container where no firewall is present?
> 

It cannot connect to DBus, so firewalld and systemd will not be used/queried.

>     * Would libvirt still detect host capabilities correctly if we start libvirt at container build time and keep the cache? Or is the pm-* scripts thing isolated enough, so that we can keep the qemu cache but not the host capabilities cache?

`pm-is-supported` is not used in the container. Not only it doesn't exist, but DBus is preferred.

**Comment by rmohr** [comment]
> I tried some things as well. I ran it inside a clean container with no capabilities present and I cannot get it to take 4 seconds even.

Sounds promising. Let me play with the pods a little bit.

**Comment by rmohr** [comment]
/close

Thanks @nertpinx  and @zippy2. At the end it was a combination of issues on the CI nodes and a weird retry strategy in kubevirt itself. As you said, it is almost instantaneous ready if the underlying infra is healthy.
